version: '3.1'
networks:
    prometheus_stack:
      external: true

services:
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:  
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
    networks:
      - prometheus_stack
  grafana:
    image: grafana/grafana:9.3.6-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - prometheus_stack
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
  prometheus:
