version: '3.1'
networks:
    prometheus_stack:
      external: true
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: promstack
      MYSQL_USER: prom
      MYSQL_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - prometheus_stack
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - prometheus_stack
volumes:
  db_data:
