version: '3'
networks:
    prometheus_stack:
      external: true
services:
  blackbox:
    image: prom/blackbox-exporter:v0.19.0
    container_name: blackbox_exporter
    networks:
      - prometheus_stack
    command:
      - --config.file=/config/blackbox.yml
      - --web.listen-address=:9115
    ports:
      - "9115:9115"
    volumes:
      - ./config:/config
    restart: unless-stopped